#                 _   _  __           _                    
#      /\        | | (_)/ _|         | |                   
#     /  \   _ __| |_ _| |_ __ _  ___| |_ ___  _ __ _   _ 
#    / /\ \ | '__| __| |  _/ _` |/ __| __/ _ \| '__| | | |
#   / ____ \| |  | |_| | || (_| | (__| || (_) | |  | |_| | 
#  /_/    \_\_|   \__|_|_| \__,_|\___|\__\___/|_|   \__, | 
#                                                    __/ |
#                                                   |___/

port = 8081

[database]

type   = "derby"
url    = "jdbc:derby:{db.home};create=true"
driver = "org.apache.derby.jdbc.EmbeddedDriver"

[storage]

binary_provider_type       = "file-system"
binary_provider_cache_size = "5000000000"

[jvm]
min_heap = "512m"
max_heap = "2g"